version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000/v1/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
