version: '3.8'

services:
  # NestJS Backend with in-memory storage
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
